#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPS_Connection_Test
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ioDB")]
	public partial class LINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InsertOfen(Ofen instance);
    partial void UpdateOfen(Ofen instance);
    partial void DeleteOfen(Ofen instance);
    partial void InsertMaterial(Material instance);
    partial void UpdateMaterial(Material instance);
    partial void DeleteMaterial(Material instance);
    partial void InsertAuftrag(Auftrag instance);
    partial void UpdateAuftrag(Auftrag instance);
    partial void DeleteAuftrag(Auftrag instance);
    partial void InsertGlühung(Glühung instance);
    partial void UpdateGlühung(Glühung instance);
    partial void DeleteGlühung(Glühung instance);
    #endregion
		
		public LINQDataContext() : 
				base(global::SPS_Connection_Test.Properties.Settings.Default.ioDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ofen> Ofen
		{
			get
			{
				return this.GetTable<Ofen>();
			}
		}
		
		public System.Data.Linq.Table<Material> Material
		{
			get
			{
				return this.GetTable<Material>();
			}
		}
		
		public System.Data.Linq.Table<Auftrag> Auftrag
		{
			get
			{
				return this.GetTable<Auftrag>();
			}
		}
		
		public System.Data.Linq.Table<Glühung> Glühung
		{
			get
			{
				return this.GetTable<Glühung>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ofen")]
	public partial class Ofen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private EntitySet<Glühung> _Glühung;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    #endregion
		
		public Ofen()
		{
			this._Glühung = new EntitySet<Glühung>(new Action<Glühung>(this.attach_Glühung), new Action<Glühung>(this.detach_Glühung));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ofen_Glühung", Storage="_Glühung", ThisKey="Id", OtherKey="Id_Ofen")]
		public EntitySet<Glühung> Glühung
		{
			get
			{
				return this._Glühung;
			}
			set
			{
				this._Glühung.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Glühung(Glühung entity)
		{
			this.SendPropertyChanging();
			entity.Ofen = this;
		}
		
		private void detach_Glühung(Glühung entity)
		{
			this.SendPropertyChanging();
			entity.Ofen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Material")]
	public partial class Material : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Position;
		
		private string _AuftragsNr;
		
		private string _Stahlsorte;
		
		private System.Nullable<int> _Charge;
		
		private System.Nullable<double> _Abmessung;
		
		private System.Nullable<int> _Anzahl;
		
		private System.Nullable<int> _Gewicht;
		
		private string _Bemerkung;
		
		private System.Nullable<int> _Id_Glühung;
		
		private int _Id_Auftrag;
		
		private EntityRef<Auftrag> _Auftrag;
		
		private EntityRef<Glühung> _Glühung;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPositionChanging(System.Nullable<int> value);
    partial void OnPositionChanged();
    partial void OnAuftragsNrChanging(string value);
    partial void OnAuftragsNrChanged();
    partial void OnStahlsorteChanging(string value);
    partial void OnStahlsorteChanged();
    partial void OnChargeChanging(System.Nullable<int> value);
    partial void OnChargeChanged();
    partial void OnAbmessungChanging(System.Nullable<double> value);
    partial void OnAbmessungChanged();
    partial void OnAnzahlChanging(System.Nullable<int> value);
    partial void OnAnzahlChanged();
    partial void OnGewichtChanging(System.Nullable<int> value);
    partial void OnGewichtChanged();
    partial void OnBemerkungChanging(string value);
    partial void OnBemerkungChanged();
    partial void OnId_GlühungChanging(System.Nullable<int> value);
    partial void OnId_GlühungChanged();
    partial void OnId_AuftragChanging(int value);
    partial void OnId_AuftragChanged();
    #endregion
		
		public Material()
		{
			this._Auftrag = default(EntityRef<Auftrag>);
			this._Glühung = default(EntityRef<Glühung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="Int")]
		public System.Nullable<int> Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuftragsNr", DbType="VarChar(10)")]
		public string AuftragsNr
		{
			get
			{
				return this._AuftragsNr;
			}
			set
			{
				if ((this._AuftragsNr != value))
				{
					this.OnAuftragsNrChanging(value);
					this.SendPropertyChanging();
					this._AuftragsNr = value;
					this.SendPropertyChanged("AuftragsNr");
					this.OnAuftragsNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stahlsorte", DbType="VarChar(50)")]
		public string Stahlsorte
		{
			get
			{
				return this._Stahlsorte;
			}
			set
			{
				if ((this._Stahlsorte != value))
				{
					this.OnStahlsorteChanging(value);
					this.SendPropertyChanging();
					this._Stahlsorte = value;
					this.SendPropertyChanged("Stahlsorte");
					this.OnStahlsorteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Charge", DbType="Int")]
		public System.Nullable<int> Charge
		{
			get
			{
				return this._Charge;
			}
			set
			{
				if ((this._Charge != value))
				{
					this.OnChargeChanging(value);
					this.SendPropertyChanging();
					this._Charge = value;
					this.SendPropertyChanged("Charge");
					this.OnChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abmessung", DbType="Float")]
		public System.Nullable<double> Abmessung
		{
			get
			{
				return this._Abmessung;
			}
			set
			{
				if ((this._Abmessung != value))
				{
					this.OnAbmessungChanging(value);
					this.SendPropertyChanging();
					this._Abmessung = value;
					this.SendPropertyChanged("Abmessung");
					this.OnAbmessungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anzahl", DbType="Int")]
		public System.Nullable<int> Anzahl
		{
			get
			{
				return this._Anzahl;
			}
			set
			{
				if ((this._Anzahl != value))
				{
					this.OnAnzahlChanging(value);
					this.SendPropertyChanging();
					this._Anzahl = value;
					this.SendPropertyChanged("Anzahl");
					this.OnAnzahlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gewicht", DbType="Int")]
		public System.Nullable<int> Gewicht
		{
			get
			{
				return this._Gewicht;
			}
			set
			{
				if ((this._Gewicht != value))
				{
					this.OnGewichtChanging(value);
					this.SendPropertyChanging();
					this._Gewicht = value;
					this.SendPropertyChanged("Gewicht");
					this.OnGewichtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bemerkung", DbType="VarChar(MAX)")]
		public string Bemerkung
		{
			get
			{
				return this._Bemerkung;
			}
			set
			{
				if ((this._Bemerkung != value))
				{
					this.OnBemerkungChanging(value);
					this.SendPropertyChanging();
					this._Bemerkung = value;
					this.SendPropertyChanged("Bemerkung");
					this.OnBemerkungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Glühung", DbType="Int")]
		public System.Nullable<int> Id_Glühung
		{
			get
			{
				return this._Id_Glühung;
			}
			set
			{
				if ((this._Id_Glühung != value))
				{
					if (this._Glühung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_GlühungChanging(value);
					this.SendPropertyChanging();
					this._Id_Glühung = value;
					this.SendPropertyChanged("Id_Glühung");
					this.OnId_GlühungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Auftrag", DbType="Int NOT NULL")]
		public int Id_Auftrag
		{
			get
			{
				return this._Id_Auftrag;
			}
			set
			{
				if ((this._Id_Auftrag != value))
				{
					if (this._Auftrag.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_AuftragChanging(value);
					this.SendPropertyChanging();
					this._Id_Auftrag = value;
					this.SendPropertyChanged("Id_Auftrag");
					this.OnId_AuftragChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Auftrag_Material", Storage="_Auftrag", ThisKey="Id_Auftrag", OtherKey="Id", IsForeignKey=true)]
		public Auftrag Auftrag
		{
			get
			{
				return this._Auftrag.Entity;
			}
			set
			{
				Auftrag previousValue = this._Auftrag.Entity;
				if (((previousValue != value) 
							|| (this._Auftrag.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Auftrag.Entity = null;
						previousValue.Material.Remove(this);
					}
					this._Auftrag.Entity = value;
					if ((value != null))
					{
						value.Material.Add(this);
						this._Id_Auftrag = value.Id;
					}
					else
					{
						this._Id_Auftrag = default(int);
					}
					this.SendPropertyChanged("Auftrag");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Glühung_Material", Storage="_Glühung", ThisKey="Id_Glühung", OtherKey="Id", IsForeignKey=true)]
		public Glühung Glühung
		{
			get
			{
				return this._Glühung.Entity;
			}
			set
			{
				Glühung previousValue = this._Glühung.Entity;
				if (((previousValue != value) 
							|| (this._Glühung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Glühung.Entity = null;
						previousValue.Material.Remove(this);
					}
					this._Glühung.Entity = value;
					if ((value != null))
					{
						value.Material.Add(this);
						this._Id_Glühung = value.Id;
					}
					else
					{
						this._Id_Glühung = default(Nullable<int>);
					}
					this.SendPropertyChanged("Glühung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Auftrag")]
	public partial class Auftrag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ODL;
		
		private string _Art;
		
		private string _Verarbeitung;
		
		private string _Status;
		
		private string _Walzung;
		
		private System.Nullable<System.DateTime> _Auftragsdatum;
		
		private System.Nullable<System.DateTime> _Liefertermin;
		
		private string _TechnischeAnmerkungen;
		
		private string _Bemerkungen;
		
		private System.Nullable<int> _SägeProgramm;
		
		private System.Nullable<double> _Anlasstemparartur;
		
		private System.Nullable<int> _Id_Kunde;
		
		private System.Nullable<int> _Id_Bestimmungsort;
		
		private EntitySet<Material> _Material;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnODLChanging(string value);
    partial void OnODLChanged();
    partial void OnArtChanging(string value);
    partial void OnArtChanged();
    partial void OnVerarbeitungChanging(string value);
    partial void OnVerarbeitungChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnWalzungChanging(string value);
    partial void OnWalzungChanged();
    partial void OnAuftragsdatumChanging(System.Nullable<System.DateTime> value);
    partial void OnAuftragsdatumChanged();
    partial void OnLieferterminChanging(System.Nullable<System.DateTime> value);
    partial void OnLieferterminChanged();
    partial void OnTechnischeAnmerkungenChanging(string value);
    partial void OnTechnischeAnmerkungenChanged();
    partial void OnBemerkungenChanging(string value);
    partial void OnBemerkungenChanged();
    partial void OnSägeProgrammChanging(System.Nullable<int> value);
    partial void OnSägeProgrammChanged();
    partial void OnAnlasstempararturChanging(System.Nullable<double> value);
    partial void OnAnlasstempararturChanged();
    partial void OnId_KundeChanging(System.Nullable<int> value);
    partial void OnId_KundeChanged();
    partial void OnId_BestimmungsortChanging(System.Nullable<int> value);
    partial void OnId_BestimmungsortChanged();
    #endregion
		
		public Auftrag()
		{
			this._Material = new EntitySet<Material>(new Action<Material>(this.attach_Material), new Action<Material>(this.detach_Material));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ODL", DbType="VarChar(10)")]
		public string ODL
		{
			get
			{
				return this._ODL;
			}
			set
			{
				if ((this._ODL != value))
				{
					this.OnODLChanging(value);
					this.SendPropertyChanging();
					this._ODL = value;
					this.SendPropertyChanged("ODL");
					this.OnODLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art", DbType="VarChar(50)")]
		public string Art
		{
			get
			{
				return this._Art;
			}
			set
			{
				if ((this._Art != value))
				{
					this.OnArtChanging(value);
					this.SendPropertyChanging();
					this._Art = value;
					this.SendPropertyChanged("Art");
					this.OnArtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verarbeitung", DbType="VarChar(50)")]
		public string Verarbeitung
		{
			get
			{
				return this._Verarbeitung;
			}
			set
			{
				if ((this._Verarbeitung != value))
				{
					this.OnVerarbeitungChanging(value);
					this.SendPropertyChanging();
					this._Verarbeitung = value;
					this.SendPropertyChanged("Verarbeitung");
					this.OnVerarbeitungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Walzung", DbType="VarChar(20)")]
		public string Walzung
		{
			get
			{
				return this._Walzung;
			}
			set
			{
				if ((this._Walzung != value))
				{
					this.OnWalzungChanging(value);
					this.SendPropertyChanging();
					this._Walzung = value;
					this.SendPropertyChanged("Walzung");
					this.OnWalzungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auftragsdatum", DbType="Date")]
		public System.Nullable<System.DateTime> Auftragsdatum
		{
			get
			{
				return this._Auftragsdatum;
			}
			set
			{
				if ((this._Auftragsdatum != value))
				{
					this.OnAuftragsdatumChanging(value);
					this.SendPropertyChanging();
					this._Auftragsdatum = value;
					this.SendPropertyChanged("Auftragsdatum");
					this.OnAuftragsdatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Liefertermin", DbType="Date")]
		public System.Nullable<System.DateTime> Liefertermin
		{
			get
			{
				return this._Liefertermin;
			}
			set
			{
				if ((this._Liefertermin != value))
				{
					this.OnLieferterminChanging(value);
					this.SendPropertyChanging();
					this._Liefertermin = value;
					this.SendPropertyChanged("Liefertermin");
					this.OnLieferterminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TechnischeAnmerkungen", DbType="VarChar(MAX)")]
		public string TechnischeAnmerkungen
		{
			get
			{
				return this._TechnischeAnmerkungen;
			}
			set
			{
				if ((this._TechnischeAnmerkungen != value))
				{
					this.OnTechnischeAnmerkungenChanging(value);
					this.SendPropertyChanging();
					this._TechnischeAnmerkungen = value;
					this.SendPropertyChanged("TechnischeAnmerkungen");
					this.OnTechnischeAnmerkungenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bemerkungen", DbType="VarChar(MAX)")]
		public string Bemerkungen
		{
			get
			{
				return this._Bemerkungen;
			}
			set
			{
				if ((this._Bemerkungen != value))
				{
					this.OnBemerkungenChanging(value);
					this.SendPropertyChanging();
					this._Bemerkungen = value;
					this.SendPropertyChanged("Bemerkungen");
					this.OnBemerkungenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SägeProgramm", DbType="Int")]
		public System.Nullable<int> SägeProgramm
		{
			get
			{
				return this._SägeProgramm;
			}
			set
			{
				if ((this._SägeProgramm != value))
				{
					this.OnSägeProgrammChanging(value);
					this.SendPropertyChanging();
					this._SägeProgramm = value;
					this.SendPropertyChanged("SägeProgramm");
					this.OnSägeProgrammChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anlasstemparartur", DbType="Float")]
		public System.Nullable<double> Anlasstemparartur
		{
			get
			{
				return this._Anlasstemparartur;
			}
			set
			{
				if ((this._Anlasstemparartur != value))
				{
					this.OnAnlasstempararturChanging(value);
					this.SendPropertyChanging();
					this._Anlasstemparartur = value;
					this.SendPropertyChanged("Anlasstemparartur");
					this.OnAnlasstempararturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Kunde", DbType="Int")]
		public System.Nullable<int> Id_Kunde
		{
			get
			{
				return this._Id_Kunde;
			}
			set
			{
				if ((this._Id_Kunde != value))
				{
					this.OnId_KundeChanging(value);
					this.SendPropertyChanging();
					this._Id_Kunde = value;
					this.SendPropertyChanged("Id_Kunde");
					this.OnId_KundeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Bestimmungsort", DbType="Int")]
		public System.Nullable<int> Id_Bestimmungsort
		{
			get
			{
				return this._Id_Bestimmungsort;
			}
			set
			{
				if ((this._Id_Bestimmungsort != value))
				{
					this.OnId_BestimmungsortChanging(value);
					this.SendPropertyChanging();
					this._Id_Bestimmungsort = value;
					this.SendPropertyChanged("Id_Bestimmungsort");
					this.OnId_BestimmungsortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Auftrag_Material", Storage="_Material", ThisKey="Id", OtherKey="Id_Auftrag")]
		public EntitySet<Material> Material
		{
			get
			{
				return this._Material;
			}
			set
			{
				this._Material.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Material(Material entity)
		{
			this.SendPropertyChanging();
			entity.Auftrag = this;
		}
		
		private void detach_Material(Material entity)
		{
			this.SendPropertyChanging();
			entity.Auftrag = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Glühung")]
	public partial class Glühung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _Erstellungsdatum;
		
		private System.Nullable<System.DateTime> _Start;
		
		private System.Nullable<System.DateTime> _Ende;
		
		private string _Name;
		
		private string _Status;
		
		private System.Nullable<int> _Tonnage;
		
		private System.Nullable<int> _Id_Ofen;
		
		private string _Id_Intern;
		
		private EntitySet<Material> _Material;
		
		private EntityRef<Ofen> _Ofen;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnErstellungsdatumChanging(System.Nullable<System.DateTime> value);
    partial void OnErstellungsdatumChanged();
    partial void OnStartChanging(System.Nullable<System.DateTime> value);
    partial void OnStartChanged();
    partial void OnEndeChanging(System.Nullable<System.DateTime> value);
    partial void OnEndeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnTonnageChanging(System.Nullable<int> value);
    partial void OnTonnageChanged();
    partial void OnId_OfenChanging(System.Nullable<int> value);
    partial void OnId_OfenChanged();
    partial void OnId_InternChanging(string value);
    partial void OnId_InternChanged();
    #endregion
		
		public Glühung()
		{
			this._Material = new EntitySet<Material>(new Action<Material>(this.attach_Material), new Action<Material>(this.detach_Material));
			this._Ofen = default(EntityRef<Ofen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Erstellungsdatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> Erstellungsdatum
		{
			get
			{
				return this._Erstellungsdatum;
			}
			set
			{
				if ((this._Erstellungsdatum != value))
				{
					this.OnErstellungsdatumChanging(value);
					this.SendPropertyChanging();
					this._Erstellungsdatum = value;
					this.SendPropertyChanged("Erstellungsdatum");
					this.OnErstellungsdatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start", DbType="DateTime")]
		public System.Nullable<System.DateTime> Start
		{
			get
			{
				return this._Start;
			}
			set
			{
				if ((this._Start != value))
				{
					this.OnStartChanging(value);
					this.SendPropertyChanging();
					this._Start = value;
					this.SendPropertyChanged("Start");
					this.OnStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ende", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ende
		{
			get
			{
				return this._Ende;
			}
			set
			{
				if ((this._Ende != value))
				{
					this.OnEndeChanging(value);
					this.SendPropertyChanging();
					this._Ende = value;
					this.SendPropertyChanged("Ende");
					this.OnEndeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(30)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tonnage", DbType="Int")]
		public System.Nullable<int> Tonnage
		{
			get
			{
				return this._Tonnage;
			}
			set
			{
				if ((this._Tonnage != value))
				{
					this.OnTonnageChanging(value);
					this.SendPropertyChanging();
					this._Tonnage = value;
					this.SendPropertyChanged("Tonnage");
					this.OnTonnageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Ofen", DbType="Int")]
		public System.Nullable<int> Id_Ofen
		{
			get
			{
				return this._Id_Ofen;
			}
			set
			{
				if ((this._Id_Ofen != value))
				{
					if (this._Ofen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_OfenChanging(value);
					this.SendPropertyChanging();
					this._Id_Ofen = value;
					this.SendPropertyChanged("Id_Ofen");
					this.OnId_OfenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Intern", DbType="NChar(8)")]
		public string Id_Intern
		{
			get
			{
				return this._Id_Intern;
			}
			set
			{
				if ((this._Id_Intern != value))
				{
					this.OnId_InternChanging(value);
					this.SendPropertyChanging();
					this._Id_Intern = value;
					this.SendPropertyChanged("Id_Intern");
					this.OnId_InternChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Glühung_Material", Storage="_Material", ThisKey="Id", OtherKey="Id_Glühung")]
		public EntitySet<Material> Material
		{
			get
			{
				return this._Material;
			}
			set
			{
				this._Material.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ofen_Glühung", Storage="_Ofen", ThisKey="Id_Ofen", OtherKey="Id", IsForeignKey=true)]
		public Ofen Ofen
		{
			get
			{
				return this._Ofen.Entity;
			}
			set
			{
				Ofen previousValue = this._Ofen.Entity;
				if (((previousValue != value) 
							|| (this._Ofen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ofen.Entity = null;
						previousValue.Glühung.Remove(this);
					}
					this._Ofen.Entity = value;
					if ((value != null))
					{
						value.Glühung.Add(this);
						this._Id_Ofen = value.Id;
					}
					else
					{
						this._Id_Ofen = default(Nullable<int>);
					}
					this.SendPropertyChanged("Ofen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Material(Material entity)
		{
			this.SendPropertyChanging();
			entity.Glühung = this;
		}
		
		private void detach_Material(Material entity)
		{
			this.SendPropertyChanging();
			entity.Glühung = null;
		}
	}
}
#pragma warning restore 1591
